version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: fooduser
      POSTGRES_PASSWORD: foodpass
      POSTGRES_DB: fooddb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    command: npm run start:prod
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=fooduser
      - DB_PASSWORD=foodpass
      - DB_DATABASE=fooddb
      - PORT=3001
      - DB_SSL=false
    ports:
      - "3001:3001"
    depends_on:
      - postgres

volumes:
  pgdata: 